(in-package #:CL-Tile)

(defun erase (mx my tsx tsy cr)
  (let* ((map (obj-array Tile-File))
	 (size-x (cadr (array-dimensions map)))
	 (size-y (car (array-dimensions map)))
	 (x (floor (/ mx (obj-tsx Tile-File))))
	 (y (floor (/ my (obj-tsy Tile-File))))
	 )
    (when (and (and (> x -1) (> y -1)) (and (< x size-x) (< y size-y)))
      (setf (aref map y x) -1)
      )
    )
  (cairo-set-operator cr :clear)
  (cairo-set-source-rgba cr 0.0 0.0 0.0 1.0)
  (cairo-rectangle cr (* (floor (/ mx tsx)) tsx) (* (floor (/ my tsy)) tsy) tsx tsy)
  (cairo-fill cr)
  )
