(in-package #:CL-Tile)

(defun erase (mx my)
  (let* ((map (obj-array Tile-File))
	 (size-x (cadr (array-dimensions map)))
	 (size-y (car (array-dimensions map)))
	 (x (mod mx (obj-tsx Tile-File)))
	 (y (mod my (obj-tsy Tile-File)))
	 )
    (when (and (and (> x -1) (> y -1)) (and (< x size-x) (< y size-y)))
      (setf (aref map y x) -1)
      )
    )
  )
